/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITokenConfiguration,
  ITokenConfigurationInterface,
} from "../ITokenConfiguration";

const _abi = [
  {
    inputs: [],
    name: "POOL",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UNDERLYING_ASSET_ADDRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITokenConfiguration__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenConfigurationInterface {
    return new utils.Interface(_abi) as ITokenConfigurationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenConfiguration {
    return new Contract(address, _abi, signerOrProvider) as ITokenConfiguration;
  }
}
